name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get scripts
      run: |
        wget -O z_10_MySQL-Main.sql https://raw.githubusercontent.com/dotnet/orleans/master/src/AdoNet/Shared/MySQL-Main.sql
        wget -O z_20_MySQL-Clustering.sql https://raw.githubusercontent.com/dotnet/orleans/master/src/AdoNet/Orleans.Clustering.AdoNet/MySQL-Clustering.sql
        wget -O z_30_MySQL-Persistence.sql https://raw.githubusercontent.com/dotnet/orleans/master/src/AdoNet/Orleans.Persistence.AdoNet/MySQL-Persistence.sql
        wget -O z_40_MySQL-Reminders.sql https://raw.githubusercontent.com/dotnet/orleans/master/src/AdoNet/Orleans.Reminders.AdoNet/MySQL-Reminders.sql

    - name: Prepare scripts
      run: |
        echo -e "USE orleans;\n$(cat z_10_MySQL-Main.sql)" > z_10_MySQL-Main.sql
        echo -e "USE orleans;\n$(cat z_20_MySQL-Clustering.sql)" > z_20_MySQL-Clustering.sql
        echo -e "USE orleans;\n$(cat z_30_MySQL-Persistence.sql)" > z_30_MySQL-Persistence.sql
        echo -e "USE orleans;\n$(cat z_40_MySQL-Reminders.sql)" > z_40_MySQL-Reminders.sql

    - name: Docker login
      uses: docker/login-action@v1.12.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker build and push
      uses: docker/build-push-action@v2.8.0
      with: 
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          fabiogouw/orleans-ready-mysql:latest
          fabiogouw/orleans-ready-mysql:v${{ github.run_number }}
